### ISSUE TITLE
[BUG] Chaos can have 4 options when "Anti-Vorime" is enabled

### ISSUE THREAD

**Issue by Museus** [ellomenop/HadesSpeedrunningMod#29]
Read title.

Probably Caused By: Chaos not being excluded from the Anti-Vorime mod
Suggested Fix: Just exclude Chaos

**Comment by ellomenop** [comment]
Affects hammers too if hammer determinism is off

**Comment by Museus** [comment]
Fixed by 0872bfccaa2553dd5e5dc011c4c125311b768f02
