### ISSUE TITLE
Can't start gameplay after installing EmoteMod on MacOS Big Sur

### ISSUE THREAD

**Issue by cwonrails** [ellomenop/HadesSpeedrunningMod#37]
On MacOS Big Sur 11.04, RC1 Modpack installs and runs correctly for all mods except `EmoteMod`. When `EmoteMod` is included in the `Mods` directory, running `modimporter.py` has successful output, but after selecting any profile (including a fresh one) the following message is displayed:

<img width="1440" alt="Screen Shot 2021-05-29 at 1 39 05 PM" src="https://user-images.githubusercontent.com/4729979/120079862-eb8bf980-c083-11eb-8a82-9af4e16bab27.png">

**Comment by Museus** [comment]
Might want to remove EmoteMod from v1.0 until we figure out the issue? @ellomenop @cgu11
