### ISSUE TITLE
ShowChamberNumber/modfile.txt missing -:

### ISSUE THREAD

**Issue by xzllzx** [ellomenop/HadesSpeedrunningMod#60]
https://github.com/ellomenop/HadesSpeedrunningModPack/blob/main/ShowChamberNumber/modfile.txt

Missing -: at start

**Comment by Zyruvias** [comment]
#63 Will fix this.

**Comment by Museus** [comment]
Closed with #63, released in https://github.com/ellomenop/HadesSpeedrunningModPack/releases/tag/v1.2.0-rc.4
