### ISSUE TITLE
Add option to set runs' starting boons to Epic rarity

### ISSUE THREAD

**Issue by SleepSoul** [ellomenop/HadesSpeedrunningMod#83]
This is among the most popular requests for new Modded features, and while it's contentious there, it's well-suited to the second ruleset, as it removes large numbers of resets for some weapons.

**Comment by Museus** [comment]
Results of Poll 1 (11/24)

59.6% ALWAYS epic
26.9% only if running Gods' Pride
13.5% only in C1
11.5% only after a reset
5.8% vanilla
