### ISSUE TITLE
Add option to remove the tiny rat enemy in Styx

### ISSUE THREAD

**Issue by SleepSoul** [ellomenop/HadesSpeedrunningMod#85]
These are some of the worst enemies in the game, especially proportionate to the normal length of Styx rooms, so removing them is a simple yet impactful optimisation.

**Comment by Museus** [comment]
Results of Poll 1 (11/24)

59.6% Yes (Starting with Tiny Rats in Styx)
17.3% Yes (Starting with something else)
23.1% No, all vanilla enemies
